### ISSUE TITLE
HA POST Candidate Updating clientStarred set coffeeConnect to false and vise versa

### ISSUE THREAD

**Issue by badluck13** [DoddleNow/DoddleNow-BackEnd#18]
How to reproduce:

- Get Ha token
- Get Client Job Candidate by ID
```
"candidateDetails": {
    "userId": "d0fbb274-f20d-4611-a7a0-6a7ea99dfa2b",
    "firstName": "Mary",
    "lastName": "Treble",
    "eMail": "maryTreble3@mailinator.com",
    "applicantApplied": false,
    "clientInterest": true,
    "clientStarred": false,
    "coffeeConnect": true,
    "exclude": false,
    "location": "Los Angeles, CA",
    "locationDistance": 0,
    "candidateGuid": "909a86a7-b636-41c4-aa65-88e4a5238657",
    "candidateAlias": "HP909A8",
    "sclMatch": 90,
    "yearsOfExperienceStr": "10+ Years"
  },
```
- Post to Update Client Job Candidate with this payload:
```
  {
    "clientStarred": true
  }
```
- Get that candidate again:
```
"candidateDetails": {
    "userId": "d0fbb274-f20d-4611-a7a0-6a7ea99dfa2b",
    "firstName": "Mary",
    "lastName": "Treble",
    "eMail": "maryTreble3@mailinator.com",
    "applicantApplied": false,
    "clientInterest": false,
    "clientStarred": true,
    "coffeeConnect": false,
    "exclude": false,
    "location": "Los Angeles, CA",
    "locationDistance": 0,
    "candidateGuid": "909a86a7-b636-41c4-aa65-88e4a5238657",
    "candidateAlias": "HP909A8",
    "sclMatch": 16,
    "yearsOfExperienceStr": "10+ Years"
  },
```
- Candidate is now starred but `coffeeConnect` and `clientInterest` is set to false in the process

This is related to DoddleNow/DoddleNow-FrontEnd#62 Candidate page logic issue on Front end branch, you can also see how this issue behaves on the server. Will deploy candidate page logic in next 10min or so.

**Comment by johnnymagic** [comment]
This is resolved.  On all of my updates in the API, I didn't account for an incomplete model being posted so expect the same issue on any update.  If this is expected on every update, I'll need to return to all update calls to accommodate.

**Comment by badluck13** [comment]
@johnnymagic I run into this again, this time with HA update job, sending partial active=false, didn't work, then sending whole model, then getting error that model is not right as there is no start and end date... We will need some time to polish all calls.

**Comment by johnnymagic** [comment]
Allowing partial updates on these HA items (more areas to follow):
**HA**
Update HA Client
Update Client Staff User
Update Client Job
Update Client Job Candidate

Let me know if one area is more important to fix next.  Otherwise, I'll just start at the top and work down.

**Comment by johnnymagic** [comment]
Finished all POSTS to accommodate partial updates.  The method names below correspond with the names in PostMan.

**Client**
Update Client
Update User under Client
Update Job under Client

**Job**
Update Job

**MyJobs**
Update HP Job by ID

**Profile**
Update Overview
Update Preferences
Update Address
Update Education
Update Certifications
Update Reference
Update Work History

**SCL**
Update Skills Checklist
Update Skills Checklist Question

**Specialties**
Update Specialty

**Users**
Update User

**Comment by badluck13** [comment]
I still get issue with **Update Client Job** active to false, tried it in postman with just "active": false and it didn't work. cc @johnnymagic
